### ISSUE TITLE
Code style standards

### ISSUE THREAD

**Issue by Pastaf** [TechnicPack/LauncherCore#20]
I use eclipse, and as seen previously I have a very odd set of style standards for most of my projects. Now, there doesn't seem to be an established norm and I want to follow one to prevent style conflicts as seen previously.

**Comment by mesl** [comment]
Have a look at [the google java standard](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html), there is even an [eclipse style file](https://google-styleguide.googlecode.com/svn/trunk/eclipse-java-google-style.xml)

**Comment by Pastaf** [comment]
This was posted in Febuary, 2014. I don't even know why it wasn't closed yet.
