### ISSUE TITLE
Excessively large logs with newer versions of Forge (1112)

### ISSUE THREAD

**Issue by psychofad** [TechnicPack/LauncherCore#24]
I hope this is the right place to post this. 

I am a modpack creator and my modpack is now causing these issues with the TechnicLauncher logs.  This is with build 439 of the launcher and seemed to start happening after my modpack started using the latest versions of Forge (1112) for Minecraft 1.7.2.  Some of it is due to the fact that Forge is now complaining when mod authors are not using the network channel communications, and the other part I have noticed is that the TechnicLauncher seems to be logging every instance when a GUI is opened.....repeatedly for as long as it is open it seems!  I am seeing 2-3GB log files daily and this is just from playing 3-4 hours a day! I was hoping there was some way to tell the launcher not to log certain events but I can find nothing in the settings.  As a temporary workaround I have symlinked my logs folder to a larger drive because my SSD can't handle these excessively large logs.  I have been reporting any mods that have the communications issue to the authors so they can work out what is going on and fix their issues but the GUI portions of the log is something the Launcher is recording that Forge does not seem to record in their logs. 

While I posted this issue in the Forum earlier, I opened my launcher...loaded my modpack...created a new save and placed down some blocks with a GUI from various mods and Minecraft and opened them.  Then I looked at the log file which was fresh (I deleted logs first) and in only 6 minutes my log file grew to be 52.5MB.  I have put the log file up on my site after deleting the UUID and accessToken of course and here is the link to it.

http://psychosis.chickenkiller.com/techniclauncher_2014-06-13.log

Let me know if you have any trouble accessing it and I can try posting it somewhere else for you as it is too big for pastebin. 

There is definately something weird going on here....I really hope this helps you track it down and get it fixed before more modpacks migrate to 1.7.2 and more mods require these newer versions of Forge or this is gonna be the first of many complaints.

**Comment by RandAlThorn** [comment]
well this post is over a year old but i found it due to finding some REDICULOUSLY large log files in my roaming technic logs folder. 70+ gig log files. After deleting the logs in that folder i recovered 483gigs of HD space. Yes id say there is an issue

**Comment by CannibalVox** [comment]
This is now fixed in v4.310.  Thanks for bugging me about it!
