### ISSUE TITLE
Clipboard Watching privacy issues.

### ISSUE THREAD

**Issue by rfox90** [TechnicPack/LauncherCore#28]
I'd rather the technic launcher didn't watch my clipboard thanks.

Could you perhaps register a service handler similar to steam:// 

i.e. technic://

I'm willing to do the research and assist you guys with this.

Messing with my clipboard all last week was not ok. Let's fix it :)

**Comment by CannibalVox** [comment]
No, a service handler is not possible without modifying your registry.

**Comment by CannibalVox** [comment]
I will make it so you can deactivate the pastewatcher though.

**Comment by rfox90** [comment]
Steam modifies my registry without asking.

Why can't technic?

**Comment by CannibalVox** [comment]
Because technic is written in java.

**Comment by rfox90** [comment]
I guess so, in which case the option to turn it off would be awesome.

**Comment by rfox90** [comment]
It appears your pastewatcher is stripping information from my pastes now.

I am unable to use technic launcher until this is fixed.

**Comment by Nentify** [comment]
Is it possible to turn off the paste watcher while the client is open? It prevents me from copying text from HexChat for some odd reason, and strips http:// from my copies as well.

**Comment by sct** [comment]
@rfox90 Easier said than done. URL protocols rely on a file location never changing. The Technic Launcher does not have an installation process. We don't store it in a static spot. A user can put the file anywhere they like which means the URL protocol can easily break if they move the file.

**Comment by rfox90** [comment]
:(, Either way please get something sorted. The launcher is very frustrating at the moment :)

**Comment by Nentify** [comment]
For now, settings the launcher to close when the MC client loads works as a fine solution for me.

**Comment by sct** [comment]
@rfox90 We are working on it night and day. We can only move so fast! Lots of updates coming very soon.

**Comment by CannibalVox** [comment]
Yeah, the major death-issues, new API, updater fixes, etc. are going stable tonight, so issues like this one are now on our radar.  I'm hoping to have a beta with some relief on this up Tuesday night.

**Comment by CannibalVox** [comment]
We stopped doin this btw
