### ISSUE TITLE
Use configured java home but use default if configured is empty

### ISSUE THREAD

**Issue by mesl** [TechnicPack/LauncherCore#31]

**Comment by mesl** [comment]
See also https://github.com/TechnicPack/LauncherV3/issues/30

**Comment by mesl** [comment]
I wanted to create a new pull request for this, but unfortunately wasn't able to due to [another pending pull request](https://github.com/TechnicPack/LauncherCore/pull/30) by me. The required changes can be viewed at https://github.com/mesl/LauncherCore/commit/a30fd3b0cef5218fa9131324ab450af8befb79b5

If needed I can create another pull request when the other one is being accepted.

**Comment by CannibalVox** [comment]
Added these separately.
